config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:edit, :update] do
    resources :bookmarks, only: [:new, :create]
  end
  resources :movies, only: [ :index, :show, :search ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  validates :overview, presence: true
  validates :title, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: :destroy
  before_action :set_list, only: [:new, :create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmarks_params)

    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show'
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmarks_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def show
    @bookmark = Bookmark.new
  end

  def destroy
    set_list
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    set_movie
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movies_params
    params.require(:movie).permit(:title, :overview, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= list.name %> list</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie, collection: Movie.all.order(:title), prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>

      </div>
      <div class="modal-footer">
          <%= f.submit 'Add movie', class: 'btn btn-flat' %>
        <% end %>
        <button type="button" class="btn btn-cancel" data-dismiss="modal">Back</button>
      </div>
    </div>
  </div>
</div>


<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Add a movie to your <%= @list.name %> list</h3>
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
          <%= f.association :movie_id, prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="cover d-flex align-items-center justify-content-center">
  <div class="text-center">
    <strong><h1>ALL MY LISTS</h1></strong>
    <h3 class="typed-js"></h3>
  </div>
</div>
<div class="container py-5">
  <div class="d">
    <h3 class="mb-0">My Lists:</h3>
  </div>
  <% @lists.each do |list| %>
    <div class="row">
      <div class="col-sm-6 align-item-center text-center">
        <%= link_to list_path(list), class:'list-name' do %>
            <%= list.name %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<br>
<em><%= link_to "Create a new list", new_list_path, class: 'btn btn-flat' %> <br>

<br>
<%= link_to "See all movies", movies_path, class: 'btn btn-flat' %></em>

app/views/lists/new.html.erb
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>Create a new list</h3>
        <%= simple_form_for @list do |f| %>
          <%= f.input :name, placeholder: 'category of choice (ex: drama, thriller...)' %>

          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<%# <%= simple_form_for(@list) do |f| %>
  <%# <%= f.input :name %>

  <%# <%= f.submit "Create a new list", class: "btn btn-primary" %> <br>
<%# <% end %>
<br>

app/views/lists/show.html.erb
<div class="position-relative">

  <h1><%= @list.name %></h1>

  <span class="movie-tag"><%= pluralize(@list.movies.size, 'movie') %></span>
</div>


<div class="container mb-5">
  <div class="d-flex justify-content-between my-4">
    <span class="mb-2 d-block"><small><em class="text-muted"><%= "You haven't saved any movies yet!" if @list.movies.empty? %></em></small></span>
    <div>
      <button type="button" class="btn btn-flat" data-toggle="modal" data-target="#new_movie_modal">
        add a movie
      </button>
      <%= link_to 'delete this list', list_path(@list), method: :delete, class: 'btn btn-cancel', data: { confirm: 'Are you sure you want to delete this list?' } %>
    </div>
  </div>
  <% @list.bookmarks.each do |bookmark| %>
    <div class="row my-2">
      <div class="col-12 col-sm-6 mb-4" data-aos="zoom-in">
        <div class="bg-white rounded shadow h-100">
          <%= image_tag bookmark.movie.poster_url, alt: bookmark.movie.title, class: 'movie-img rounded-top', height: 900, width: 600 %>
          <div class="p-3 rounded-bottom d-flex flex-column">
            <strong><%= bookmark.movie.title %> <span class="text-muted font-weight-normal">• <%= bookmark.movie.rating %> <i class="fas fa-star star-yellow"></i></span></strong>
            <small class="text-muted"><%= bookmark.movie.overview %></small>
            <div class="d-flex align-items-end justify-content-between pt-4">
              <div>
                <i class="fas fa-quote-left mr-2"></i><small class="flex-grow-1"><%= bookmark.comment %></small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>


<div class="modal fade" id="new_movie_modal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add a movie to your <%= @list.name %> list</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.input :movie_id, collection: Movie.all.order(:title), prompt: 'Select a movie', input_html: { class: 'select2' } %>
          <%= f.input :comment, placeholder: 'Enter a comment about the movie' %>
      </div>
      <div class="modal-footer">
          <%= f.submit 'Add movie', class: 'btn btn-flat' %>
        <% end %>
        <button type="button" class="btn btn-cancel" data-dismiss="modal">Back</button>
      </div>
    </div>
  </div>
</div>

<%= link_to "go back to all the lists", lists_path %> <br>

app/views/movies/index.html.erb
<h1> All movies: </h1>
<% @movies.each do | movie | %>

<div class="movie">
  <%= link_to movie.title, movie_path(movie) %> <br>

  <%= image_tag movie.poster_url, alt: "poster" %>
  <%= movie.overview %> <br>
  <%= movie.rating %> <br>
  <% end %>
</div>

<br>
<%= link_to "See all lists", lists_path %> <br>

<%= link_to "create a new list", new_list_path %>
<%# <%= link_to "Search a new movie", movie_path %>

app/views/movies/new.html.erb
<%= simple_form_for(@movie) do |f| %>
  <%= f.input :title %>

  <%= f.submit "Search movie", class: "btn btn-primary" %>
<% end %>

app/views/movies/show.html.erb
<div class="add-movie-to-list">
  <%= @movie.title %>
  <%= @movie.overview %>
  <%= @movie.rating %>
  <%= image_tag @movie.poster_url, alt: "poster", width: 100 %>
</div>

<div class="go-back-to-movies">
  <%= link_to "go back to all the movies", movies_path %> <br>
</div>
<%# <%= simple_form_for [@movie, @list] do |f| %>
      <%#     <%= f.association :list, collection: List.all.order(:name), prompt: 'Select a list', input_html: { class: 'select2' } %>
      <%#     <%= f.button :submit %>
    <%#   </div>
exit